### ISSUE TITLE
Cannot run F360 addins from other addins

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aide#1]
@ethan92429 In order to implement your solution of having aide call aide_gui, we would have to have the F360 command (from the aide Add In) to run the palette_gui Add In, which would be nearly impossible.

So we have aide and palette_gui addin code folders within the API/AddIns folder on our computers, and within the aide AddIn code, we would have to import the palette_gui code to run the palette_gui AddIn. However, we can't do `from .. import palette_gui` (essentially going up two levels in the file system) because python doesn't allow it. Furthermore, we can't just put the palette_gui folder within the aide folder because F360 must run addins from the API/AddIns, not within any subfolders.

One workaround could be to hard code an absolute path to the palette_gui folder to import, but I want to avoid doing that.

Because of this, would it just be easier to have the user open up the palette_gui and then have the gui run all of aide's stuff?

[Here is a forum post](https://forums.autodesk.com/t5/fusion-360-api-and-scripts/run-addin-from-script/m-p/7728909) (from our good friend Marshal!) which says that it's impossible to run AddIns/Scripts from Scripts; I'm assuming that the same goes for running AddIns/Scripts from AddIns and their Commands.

**Comment by ethan92429** [comment]
We will have only one addin. The aide_gui will get called from the AIDE
addin. The AIDE gui is a package that lives within AIDE. More specifically,
it will be downloaded at installation and installed within AIDE. For now,
Hardcode your site packages path to give fusion a path to your global
packages. Something like: sys.path.append(your site packages path). This
way you don't have to worry about that install step until later. That work?
