### ISSUE TITLE
I can't write on the discussion board

### ISSUE THREAD

**Issue by AppTeamComposer** [AguaClara/aide#12]
The input box is unresponsive when I click on it. I can't reply to anything either

**Comment by oliver-leung** [comment]
Are you referring to the [AIDE](https://github.com/orgs/AguaClara/teams/aide) and [AIDE Template](https://github.com/orgs/AguaClara/teams/aide-template) discussion boards? It looks like you're already a member of both of them, and you're a member of the GitHub Organization for AguaClara.

I tried to reset your membership status for all of them - can you test to see if it works now? If not, I can take a look at it tomorrow in lab, or tonight after class.
