### ISSUE TITLE
Combine aide_gui with aide

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aide#2]
After working with the Fusion 360 API for a while, I still think that combining the functionality of aide and aide_gui would be the best way to integrate all of our modules. By that, I mean that aide_gui (which would reasonably be renamed to aide) will gather user inputs, then subsequently call aide_design/draw/document while passing those inputs as parameters. Combining the two would allow us to both avoid the shortcomings of the F360 API and more easily add functionality in the future.

# Why aide can't call aide_gui
I ran minimal tests on as many of the following ideas as I could, but let me know if anything seems out of place and I'll retest it.
## Returning user inputs
As is currently planned out in the [ReadMe's](https://github.com/AguaClara/aide/blob/master/README.md) MVP1, running aide_gui will return the location of the YAML containing the gathered user inputs. This can't be done for the following reasons:
1. The user inputs can't be returned immediately when aide_gui is run because they don't yet exist. aide_gui would be pushed off of the call stack and aide would hand off an incomplete YAML to aide_design.
2. The user inputs can't be returned when the user inputs their parameters because Python will get "impatient" and just return `None` if a return value isn't given immediately.

These problems stem from the fact that F360 add-ins use event handlers, so let's see what happens when we play around with them.
## Event handling
Instead of having aide_gui return the user inputs, I tried having it trigger an event that would notify aide that the user inputs had been written to a YAML. As seen in [aide.py](https://github.com/AguaClara/aide/blob/master/aide.py) and [aide_gui.py](https://github.com/AguaClara/aide_gui/blob/spring-2018/aide_gui.py), event handlers for add-ins are stored in a globally declared `handlers` list. In order for this to work, we'll need for aide and aide_gui to be able to "share" this list, either by having aide_gui return its `handlers` to aide, or by aide passing its `handlers` as a parameter when calling `aide_gui.run`.

Having aide_gui return its `handlers` won't work for similar reasons to why aide_gui can't simply return the location user inputs:
1. The `handlers` can't be returned at the end of `aide_gui.run` because by that point, only one event handler (`ShowPaletteCommandCreated`) will be appended. There are two others that are needed for aide_gui to work (`ShowPaletteCommandExecute` and `MyHTMLEvent`), and with `aide_gui.run` pushed off of the call stack, there's no way to return those other handlers to aide.
2. The `handlers` can't be returned after two or three handlers are appended because Python will get "impatient" and just return `None`.
3. The `notify` functions for each event only act within the add-in where they're called (aide_gui in this case), and because they're called from the backend of F360, we can't manually call them from aide.

Having aide pass its `handlers` list to aide_gui would require the list to be passed it through each of the handlers' `__init__(self)` and `notify(self, args)` functions so that it gets appended to. This isn't possible, because the F360 backend expects for there to only be the provided `self` and `args` (in `notify`) parameters to be passed and throws an exception when more are given. Even if we managed to get all of the handlers successfully appended, there's still no way for us to get them back to aide for the above reasons.

Overall, the current system of aide being the master controller forces us to use the F360 API in a way that it's not designed for. There should only be one add-in running at a time, rather than an add-in within an add-in.
# Why combining aide and aide_gui is a good solution
## Sequential use of aide modules
We discussed the idea that we would want to make aide modular so that each module could be self-contained, and that modules shouldn't reference one another. If we make aide_gui the controller, we can maintain this modularity while still being able to run each module after the preceding module is done.

Here's some pseudocode for how this would look, based off of the current state of aide_gui.py:
```python
def run():
    showPalette()
def showPalette():
    HTMLEvents.beginHandling()
    DesignEvents.beginHandling()
    DrawDocEvents.beginHandling()
def HTMLEventHandler():
    navigate_gui()
    if HTMLEvent is user_input:
        write(user_input, yaml_path)
        DesignEvent.execute()
def DesignEventHandler():
    # NOTE: The location of the design repository and its associated files can be stored in the YAML.
    aide_design(yaml_path)
    DrawDocEvent.execute()
def DrawDocEventHandler():
    aide_draw(yaml_path)
    aide_document(yaml_path)
```
## Communicating with the user
Combining aide and aide_gui would make it much easier to convey when each part of the design process is finished by displaying a different page when each module is being run. Additionally, it would make for an overall better experience for the user when they can see what aide is doing at the moment.

**Comment by eldorbekpulatov** [comment]
I completely support that

**Comment by ethan92429** [comment]
Great research.

I agree we absolutely shouldn't have gui and AIDE be two different addins.
I think I said gui would be a different package within the addin. Does that
make sense? AIDE gui itself has no need for a run function, since it is
used as a package that gets called from the AIDE addin. The AIDE addin is
the overall pseudocode we've written thus far, and all the AIDE packages
that have been written so far are called from the AIDE master code. Does
that make more sense? The reasoning is that keeping them as different
packages helps delineate the interfaces between the AIDE component. In
Python, interfaces are not well defined, so we need to be judicious and
intentional when drawing them - more so than in a compiled language like c.
For instance, I am busy writing another version of AIDE draw that can draw
to onshape rather than fusion 360. For that, I also need to build a new
gui, but I wouldn't need a new document or design or render. Think of gui,
draw, design, document as dependencies of aide.

**Comment by oliver-leung** [comment]
We are implementing the [Observer pattern](https://en.wikipedia.org/wiki/Observer_pattern) technique in order to run aide_design/draw/document sequentially after user inputs have been collected.
