### ISSUE TITLE
Standardize Build Function format and determine if it can be made modular since all components will have a very similar build function.

### ISSUE THREAD

**Issue by monroews** [AguaClara/aide#22]
The build function brings in 
* Hydraulic Design Functions from AC
* expert inputs that are passed down from higher level
and creates a configuration with the variables that are defined in HDF.
* what else does it do???

**Comment by ethan92429** [comment]
Correspondingly, the Build Feature is very small. The intention is that it could hold and reason about any geometric setup needed, and if that isn't needed - leave it out. I don't see many ways to cut down the number of lines here, it is quite declarative already. Is there some concern I'm not understanding? @monroews @oliver-leung

**Comment by ethan92429** [comment]
To note, the other thing it will do is be able to choose between several different PartStudios depending on the inputs. This is pretty complex for the higher level components.

**Comment by monroews** [comment]
Understood. I was overwhelmed because I don't understand FeatureScript yet and so I can't tell what the code is doing. I was hoping there was a way to package this into a more user friendly form. Let's make sure that the featurescript team is able to understand how the BF works so that they can create BF for the other unit processes.
