### ISSUE TITLE
Define feature build order for DPS

### ISSUE THREAD

**Issue by monroews** [AguaClara/aide#23]
1) Design basis
     a) expert inputs
     b) expert inputs overrides
     c) HDF 
2) sketches based on variables from HDF

**Comment by ethan92429** [comment]
To flesh this out a little more, I think the task is to actually document this order. I recommend someone make a wiki based on the [presentation here](https://docs.google.com/presentation/d/1IN7FrOn898iQvagyljx975tX94lk1ey6PZFZoLCnCSc/edit?usp=sharing) which is still ongoing.

**Comment by oliver-leung** [comment]
I've created a video documenting the 3-Level Design [here](https://youtu.be/WJLB5NgiK8Q), but please re-open this issue if you believe that we can go further with this documentation!
