### ISSUE TITLE
SuperDerive bugs

### ISSUE THREAD

**Issue by monroews** [AguaClara/aide#49]
1. Superderive throws errors when the geometry is suppressed and the mate connector is missing. Ideally this error would be eliminated since the mate connector isn't used if the geometry is suppressed.
2. Many of our uses of superderive throw an error because there is a bad string in the "Configuration JSON or Map". This is because line 151 of SuperDerive is `const configurationStringDefault = '\\\"{"my_parameter_id": "my_value"}\\\"';` Thus when that input isn't used it causes an errror.

**Comment by fletchapin** [comment]
Completed in Version 50 of Super Derive: https://cad.onshape.com/documents/c81fce53dede81ef89860aa3/v/b0148c1857f1370edb55358c/e/b453944163f91ccf1477e3f0
