### ISSUE TITLE
Pip install for dependency packages

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aide#5]
Instead of leaving the entire source distributions (sdists) of the packages for our dependencies, we should instead be trying to run a local pip install on the user's computer. See [this forum post](https://forums.autodesk.com/t5/fusion-360-api-and-scripts/installing-a-python-package-with-pip-from-within-a-script/td-p/7807746) for more information on our progress.

**Comment by ethan92429** [comment]
@oliver-leung abandon the idea of using pip. This is too complex. Instead, I'll write a short Travis script that pip installs the required packages and pushes the aide package +the dependencies in one fell swoop. This way we don't have to think about pip, but we also don't have to figure out how to make it work in the Fusion environment.

**Comment by oliver-leung** [comment]
@ethan92429 Is [this](https://docs.travis-ci.com/user/languages/python/#pip) what you're talking about for the Travis script? If so, I can add it to each of the AIDE modules.
