### ISSUE TITLE
Create "configurations" which are easier to update than hardcoded variables but less visible than current GUI

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide#57]
Add “configurations” which would be easier to update than hardcoded variables but not available to the user (like expert inputs are). For example, the dimensions of bolts to use in the CDC should be configured in case we need to update it but never needs to be exposed to the user.

Right now, everything is visible to the user in a GUI and quickly becomes daunting.

**Comment by oliver-leung** [comment]
Are you thinking of implementing this in a new feature type?

**Comment by fletchapin** [comment]
Not exactly sure how we'll implement it. We could create a document which saves all these hardcoded values so there's one place to update/import them, or it could be more complex than that

**Comment by oliver-leung** [comment]
Just to be sure, by "hardcoded", do you mean literally typed out in a Feature Studio, or could it also be input values to Features in a Part Studio?
