### ISSUE TITLE
Team restructuring for Fall 2018

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aide#7]
I've been thinking about how we can improve upon the current structure of the AIDE subteam and where we're headed in the coming academic year. Here are some ideas I have:

## More Github, less GDrive

Upon cleaning out the [AIDE GDrive folder](https://drive.google.com/open?id=0B_v6wpES3UAuRW5vQXViOEt2TUk) (which was pretty messy), I realized that _the vast majority of our organizational tools can be ported over to the functionality in Github_: issues for to-do's, discussion boards for status updates, etc. I think the GDrive folder should only be used for:

- Files that don't work well with Github repos (e.g. our presentations, drawings/diagrams)
- Documents that need to be updated and written to by multiple people at the same time

Everything else should go in AIDE repositories, wikis, or AIDE teams' discussion boards. The benefit of this is that it reduces the amount of maintaining we'll have to do, and it will make AIDE team members more comfortable with using Github - something they'll inevitably have to do in their future careers.

## Less specialization of coding teams

AIDE members almost always fall into one of two skill sets: _CAD-ing_ and _coding_. There's definitely no expectation that team members should switch between those two skill sets. As such, AIDE Template should remain as a discrete (sub-)sub-team within AIDE.

But instead of having sub-teams that each specialize in a single AIDE module, I believe we should have _general coding teams that can work on any module necessary_. This could take the form of 2-3 coding teams (called AIDE Code A/B/C, or perhaps something that doesn't imply a hierarchy 😝), such that each team's members are working together for the entire semester. These coding teams wouldn't be tied down to a single AIDE module, and instead would have the freedom to switch between working on different modules.

### Benefits

- Team members will have a better, broader understanding of the entire AIDE tool and different software development tools
- Exposing more people to the same problem can bring in new ideas
- Avoid burnout on difficult tasks

### Drawbacks

- It will take much longer for a new team member to jump in
- Switching modules/problems will take extra time and energy

## Better coherence as a team

To resolve some of the above drawbacks, we should _actively build coherence of AIDE as a centralized subteam, rather than a bunch of sub-sub-teams._ When I first joined AIDE, I didn't quite understand _why_ I was doing what I was doing, and as a result, our work was confused and we sometimes had to backtrack. The first priority for AIDE in a given semester is that each team member understands:

1. What the AIDE tool is intended to accomplish for the end user
2. How each AIDE module works and interacts within the entire AIDE tool
3. How to write good code that is easy to read and understand

When new members join, they should be _required to complete both the [AguaClara Tutorial](https://github.com/AguaClara/aguaclara_tutorial) and the [AIDE Tutorial](https://github.com/AguaClara/aide_tutorial)_. There's a lot of knowledge in the AguaClara Tutorial that would be useful for AIDE members, especially with using Git and Github. I'm working on improving both tutorials to ease new members into the AIDE workflow.

It's also important that the _subteam's leadership is actively interacting with team members_ so that they know someone to turn to when they run into problems. For this, we could hold monthly team meetings - similar to the current leadership meetings, but with more involvement (as AIDE is so large, I don't expect everyone to be able to attend, but at least one person from each team should).

To facilitate teams switching between different modules/problems, we should have _"pivots": meetings in which one team teaches another team_ about what they've accomplished with their module, and provides tips on how to continue. These pivots will continually build on the team members' understanding of AIDE.

## Semester-long planning

There are about 15 weeks from when new AguaClara team members join to the final presentations - we'll have to plan wisely. A possible schedule:

- **1-2 weeks**: Learning about how AIDE works, old members teach new members
- **5-6 weeks**: Adding features, tackling problems, pivots, team meetings
- **1 week**: "Frozen code", during which no new features are added. Ensure that code is well written and documented, culminating in code reviews
- ***Mid-semester Symposium***
- **5-6 weeks**: Adding features, tackling problems, pivots, team meetings
- **1 week**: "Frozen code"
- ***Final Presentations***

**Comment by ethan92429** [comment]
@oliver-leung Is this proposed restructuring for 2018? Thanks for starting this and looking ahead! 

Here are my (unsolicited) two cents!

aide_draw and aide_gui can be virtually eliminated - their work is done. Except for perhaps a team that could add OnShape to the cad systems supported.

I'm unclear what aide_document has left to do and I'm hesitant to have an aide_document team because the initial goal of copying the documentation engine of the earlier design tool is trivial. Before we proceed with aide_document, we need direct feedback from the field and to see a completed design. A huge part of documentation yet to be accomplished is technical drawings... 

The main thing missing is the connection between the CAD team (aide_template) and aide_design. These teams should be working next to one another all the time.

**Comment by oliver-leung** [comment]
Definitely agree for `aide_draw` and `aide_gui`! Their work is basically complete. However, I do want to continue maintaining what we currently have and refactoring it so that future team members will be able to more easily jump into them. I saw this really good [presentation](https://www.youtube.com/watch?v=56mETnrByBM) on writing readable code, and I think it would be a good idea to use those ideas to refactor what we currently have. We could also make a style guide and tutorial on those ideas.

I'm interested in seeing the doc engine from the earlier design tool, do you know where I could find that?

Sorry I forgot to update and elaborate on the ideas I had above! I'll get to that soon.

@ethan92429

**Comment by ethan92429** [comment]
@oliver-leung thank you for the thorough and thoughtful reflections. I agree that this coming semester we should transition to a smaller, more focused team - We simply won't have the need for several disparate teams because AIDE will be integrated. Having a good wiki and onboarding process is **very critical** to get students up to speed and I think it's wonderful that you are working on this! Let's keep discussing this when I'm up next week and the week of the 6th of August.
